version: '3.7'

services:
  identity:
    container_name: FFXIVVenues.Identity
    image: ffxivvenues/ffxivvenues.identity:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - FFXIVVenues.Network
      - FFXIVVenues.Identity.Network
    environment:
      - FFXIVVENUES_IDENTITY__ConnectionStrings__Identity=Host=FFXIVVenues.Identity.Postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=identity

  postgres:
    container_name: FFXIVVenues.Identity.Postgres
    image: postgres
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=identity
    volumes:
      - FFXIVVenues.Identity.Postgres.Volume:/var/lib/postgresql/data

networks:
  FFXIVVenues.Network:
    external: true
  FFXIVVenues.Identity.Network:

volumes:
  FFXIVVenues.Identity.Postgres.Volume:
