version: '3.7'

services:
  identity:
    container_name: FFXIVVenues.Identity
    image: ffxivvenues/ffxivvenues.identity:latest
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - FFXIVVenues.Network
      - FFXIVVenues.Identity.Network
    environment:
      - FFXIVVENUES_IDENTITY__CONNECTION_STRING=postgresql://postgres:${POSTGRES_PASSWORD}@FFXIVVenues.Identity.Postgres/ffxivvenues

  postgres:
    container_name: FFXIVVenues.Identity.Postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ffxivvenues
    volumes:
      - FFXIVVenues.Identity.Postgres.Volume:/var/lib/postgresql/data

networks:
  FFXIVVenues.Network:
    external: true
  FFXIVVenues.Identity.Network:

volumes:
  FFXIVVenues.Identity.Postgres.Volume:
