version: '3.7'

services:
  app:
    image: ffxivvenues/ffxivvenues.identity:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - public
      - network
    environment:
      - FFXIVVENUES_IDENTITY__ConnectionStrings__Identity=Host=FFXIVVenues.Identity.Postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=identity

  postgres:
    image: postgres
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=identity
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - network

networks:
  public:
    external: true
  network:

volumes:
  postgres-volume:
